# Generated by Django 4.0.1 on 2022-02-26 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=40)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
    ]
