# Generated by Django 4.0.1 on 2022-02-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marketing',
            field=models.BooleanField(default=True),
        ),
    ]
