# Generated by Django 4.0.1 on 2022-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_marketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
